"""empty message

Revision ID: 57662fd08118
Revises: f6df734fac64
Create Date: 2023-04-04 21:44:18.151117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57662fd08118'
down_revision = 'f6df734fac64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('age', sa.String(length=2), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('race', sa.String(length=80), nullable=False),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
