"""empty message

Revision ID: 97c33ca443cf
Revises: bbbcabf57b2f
Create Date: 2023-04-10 23:49:53.825169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c33ca443cf'
down_revision = 'bbbcabf57b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_image', sa.String(length=350), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=700), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('url_image')

    # ### end Alembic commands ###
