"""empty message

Revision ID: f6df734fac64
Revises: 22bbd6dfc26b
Create Date: 2023-04-03 23:08:21.966778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6df734fac64'
down_revision = '22bbd6dfc26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_medic_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_medic_key', ['medic'])

    # ### end Alembic commands ###
